# Generated by Django 4.1.7 on 2023-03-02 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('working', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Computer', 'Computer'), ('IT', 'IT'), ('Electrical', 'Electrical')], default=None, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('city', models.CharField(choices=[('Rajkot', 'Rajkot'), ('Ahmadabad', 'Ahmadabad'), ('Amreli', 'Amreli'), ('Baroda', 'Baroda')], default='Rajkot', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
