# Generated by Django 4.1.7 on 2023-02-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_address', models.CharField(max_length=150)),
                ('employee_working', models.BooleanField(default=True)),
                ('employee_department', models.CharField(max_length=10)),
            ],
        ),
    ]
