# Generated by Django 4.1.7 on 2023-02-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeData',
            new_name='EmployeeData2',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
