# Generated by Django 4.1.7 on 2023-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee2', '0002_rename_employeedata_employeedata2_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Rajkot', 'Rajkot'), ('Ahmedabad', 'Ahmedabad'), ('Amreli', 'Amreli'), ('Baroda', 'Baroda')], default='Rajkot', max_length=25)),
            ],
        ),
    ]
