# Generated by Django 4.1.7 on 2023-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_teacher',
            field=models.ManyToManyField(to='student.teacher'),
        ),
    ]
